- hosts: "localhost"
  connection: "local"
  tasks:
  - name: Enable UFW
    community.general.ufw:
      state: enabled
  - name: Deny incoming
    community.general.ufw:
      policy: deny
      direction: incoming
  - name: Allow monitoring
    community.general.ufw:
      src: 10.244.0.0/16
      rule: allow
      proto: tcp
      direction: in
  - name: Allow I don't know
    community.general.ufw:
      src: 10.43.0.0/16
      rule: allow
      proto: tcp
      direction: in
  - name: Allow I don't know
    community.general.ufw:
      src: 10.42.0.0/16
      rule: allow
      proto: tcp
      direction: in
  - name: Allow all on private
    community.general.ufw:
      src: 10.0.0.0/16
      rule: allow
      proto: tcp
      direction: in
  - name: Change ssh port
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^Port\s"
                line="Port ${PORT}"
                state=present
    notify: Restart ssh
  - name: Disallow root SSH access
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PermitRootLogin"
                line="PermitRootLogin prohibit-password"
                state=present
    notify: Restart ssh
  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PasswordAuthentication"
                line="PasswordAuthentication no"
                state=present
    notify: Restart ssh
  - name: Add the user lingwood
    user:
      name: lingwood
      comment: Chris Lingwood
      group: sudo
      shell: /bin/bash
  - name: "Add authorized keys"
    authorized_key:
      user: lingwood
      key: https://github.com/lingwooc.keys
  - name: Install jq
    apt:
      name: jq 
      state: present
  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
